stages:
  - lint
  - backup

# 🧪 ShellCheck Lint Job
lint:shellcheck:
  stage: lint
  image: koalaman/shellcheck:stable
  script:
    - shellcheck rsync_backup.sh
  only:
    - merge_requests
    - branches

# 🔄 Rsync Backup Job
rsync_backup:
  stage: backup
  script:
    - chmod +x rsync_backup.sh
    - ./rsync_backup.sh
  only:
    - schedules
    
